ORTH = 0
LOWER = 1
SHAPE = 2
LENGTH = 3
IS_ALPHA = 4
IS_DIGIT = 5
IS_PUNCT = 6
IS_SPACE = 7
LIKE_NUM = 8
IS_ASCII = 9

TEXT = ORTH

IDS = {
    "ORTH": ORTH,
    "TEXT": ORTH,
    "LOWER": LOWER,
    "SHAPE": SHAPE,
    "LENGTH": LENGTH,
    "IS_ALPHA": IS_ALPHA,
    "IS_DIGIT": IS_DIGIT,
    "IS_PUNCT": IS_PUNCT,
    "IS_SPACE": IS_SPACE,
    "LIKE_NUM": LIKE_NUM,
    "IS_ASCII": IS_ASCII,
}
